### PR TITLE
feat: update to node 20

### PR DESCRIPTION
**Pull request by jonathannorris**

### CODE REVIEW

**Comment by jonathannorris** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #648** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/js-sdks/648?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/DevCycleHQ/js-sdks/648?utm_source=stack-comment).

**Review by ajwootto — COMMENTED** [review]
looks like the build step never completed

**Comment by jonathannorris** [comment]
@ajwootto not sure if there is an easy way to get CI to trigger all the tests, but I ran them locally: 
image

**Comment by ajwootto** [comment]
> @ajwootto not sure if there is an easy way to get CI to trigger all the tests, but I ran them locally: image

the most correct way would be to tell Nx about other files it should watch to consider things "changed". There's an `nx.json` setting for that, where you can add things like `.nvmrc` and the github action yamls as something it should monitor. However I think the tests passing locally is good enough to merge this.

**Review by ajwootto — APPROVED** [review]

**Pull request merged**
