### PR TITLE
feat: move NodeJS OpenFeature Provider into NodeJS SDK, using `getOpenFeatureProvider()` method

### PR DESCRIPTION
**Pull request by jonathannorris**
move NodeJS OpenFeature Provider into NodeJS SDK. The new `getOpenFeatureProvider()` method will return a DevCycle OpenFeature Provider with an initialized NodeJS SDK.

This will simplify the initialization of using DevCycle with OpenFeature to just:
```javascript
    await OpenFeature.setProviderAndWait(
        initializeDevCycle(DEVCYCLE_SERVER_SDK_KEY).getOpenFeatureProvider(),
    )
    openFeatureClient = OpenFeature.getClient()
```

Deleting the old provider, which was a separate package, will mark it as deprecated when this is released and update the NPM page to point to the main NodeJS SDK.

### CODE REVIEW

**Comment by jonathannorris** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #707** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/js-sdks/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/DevCycleHQ/js-sdks/707?utm_source=stack-comment).

**Review by JamieSinn — APPROVED** [review]
Is this technically a major vbump too since its breaking?

**Comment by jonathannorris** [comment]
@JamieSinn nope not breaking, just adding functionality to the Node SDK, old open feature provider package will continue to work.

**Comment by jonathannorris** [comment]
The test harness will be broken until this is merged because of the removed `openfeature-nodejs-provider`

**Review by ajwootto — APPROVED** [review]

**Pull request merged**
